import numpy as np
import json
import os
from pathlib import Path

# --- SfePy Imports for real 3D Finite Element Analysis ---
from sfepy.discrete import Problem
from sfepy.discrete.fem import Mesh, FEDomain, Field
from sfepy.discrete import FieldVariable, Material, Integral, Equation, Equations
from sfepy.terms import Term
from sfepy.solvers.ls import ScipyDirect
from sfepy.solvers.nls import Newton
from sfepy.solvers.evp import LOBPCGSolver

def get_orthotropic_stiffness_3d(material_dict):
    """
    Converts 9 engineering constants (E, nu, G) into a 6x6 stiffness matrix (C).
    This matrix represents the material's elastic behavior in 3D.
    """
    EL, ET, ER = material_dict['E_L'], material_dict['E_T'], material_dict['E_R']
    vLT, vLR, vTR = material_dict['nu_LT'], material_dict['nu_LR'], material_dict['nu_TR']
    GLT, GLR, GTR = material_dict['G_LT'], material_dict['G_LR'], material_dict['G_TR']

    # Maxwell's relations for symmetry
    vTL = vLT * (ET / EL)
    vRL = vLR * (ER / EL)
    vRT = vTR * (ER / ET)

    # Compliance Matrix (S)
    S = np.zeros((6, 6))
    S[0, 0], S[1, 1], S[2, 2] = 1.0/EL, 1.0/ET, 1.0/ER
    S[0, 1] = S[1, 0] = -vLT / EL
    S[0, 2] = S[2, 0] = -vLR / EL
    S[1, 2] = S[2, 1] = -vTR / ET
    S[3, 3], S[4, 4], S[5, 5] = 1.0/GLT, 1.0/GLR, 1.0/GTR

    # Stiffness Matrix (C) is the inverse of S
    return np.linalg.inv(S)

def solve_3d_eigenmodes(mesh_file, C_matrix, density, num_modes=30):
    """
    Core Numerical Solver: 
    Solves the generalized eigenvalue problem: K * u = lambda * M * u
    """
    # 1. Load the 3D mesh generated by Gmsh
    mesh = Mesh.from_file(mesh_file)
    domain = FEDomain('domain', mesh)
    omega = domain.create_region('Omega', 'all')
    
    # 2. Define Displacement Field (3 components for 3D: x, y, z)
    field = Field.from_args('fu', np.float64, 3, omega, approx_order=1)
    u = FieldVariable('u', 'unknown', field)
    v = FieldVariable('v', 'test', field)
    
    # 3. Define Material Properties
    m = Material('m', D={'C': C_matrix, 'rho': density})
    integral = Integral('i', order=2)
    
    # 4. Define Linear Elasticity and Mass Terms
    # dw_lin_elastic corresponds to the Stiffness Matrix (K)
    # dw_volume_dot corresponds to the Mass Matrix (M)
    t1 = Term.new('dw_lin_elastic(m.C, v, u)', integral, omega, m=m, v=v, u=u)
    t2 = Term.new('dw_volume_dot(m.rho, v, u)', integral, omega, m=m, v=v, u=u)
    
    # 5. Set up the Problems
    pb_k = Problem('stiffness', equations=Equations([Equation('balance', t1)]))
    pb_m = Problem('mass', equations=Equations([Equation('mass', t2)]))
    
    # 6. Initialize the Eigenvalue Solver (LOBPCG)
    evp_solver = LOBPCGSolver({'kind': 'eig.scipy', 'i_max': 150})
    
    # 7. Assemble Matrices
    print("Assembling K and M matrices...")
    mtx_k = pb_k.equations.evaluate(mode='weak', dw_mode='matrix', term_mode='stiffness')
    mtx_m = pb_m.equations.evaluate(mode='weak', dw_mode='matrix', term_mode='mass')
    
    # 8. Solve the Eigenvalue Problem
    print(f"Solving for first {num_modes} modes...")
    eigs, vecs = evp_solver(mtx_k, mtx_m, n_eigs=num_modes)
    
    # 9. Convert Radian Frequencies to Hertz
    freqs = np.sqrt(np.maximum(eigs, 0)) / (2 * np.pi)
    return sorted(freqs.tolist())

def run_fem_3d_simulation(config_path):
    """
    Pipeline orchestrator: Reads config, calls solver, and saves JSON output.
    """
    if not os.path.exists(config_path):
        print(f"ERROR: Config file {config_path} not found.")
        return

    with open(config_path, 'r') as f:
        config = json.load(f)
    
    print(f"--- STARTING REAL 3D FEM SIMULATION ---")
    wood_props = config['materials']['wood']
    C_matrix = get_orthotropic_stiffness_3d(wood_props)
    mesh_file = config['solver']['mesh_file']

    if not os.path.exists(mesh_file):
        print(f"ERROR: Mesh file {mesh_file} not found! Run Geometry Preview first.")
        return

    try:
        # EXECUTE THE REAL CALCULATION
        real_modes = solve_3d_eigenmodes(
            mesh_file, 
            C_matrix, 
            wood_props['density'], 
            config['solver']['num_modes']
        )
    except Exception as e:
        print(f"FEM Solver encountered a fatal error: {e}")
        return

    # Prepare data for STK and GUI
    output_data = {
        "material": wood_props['name'],
        "modes_hz": real_modes,
        "amplitudes": [1.0] * len(real_modes),
        "dimensions": config['geometry']
    }
    
    # Output Management
    output_dir = Path("FEM/outputs")
    output_dir.mkdir(parents=True, exist_ok=True)
    output_path = output_dir / "fem_3d_output.json"
    
    with open(output_path, 'w') as f:
        json.dump(output_data, f, indent=4)
    
    print(f"SUCCESS: 3D frequencies saved to {output_path}")
    return output_path

if __name__ == "__main__":
    # Test path when running script directly
    test_config = Path(__file__).resolve().parents[1] / "configs" / "guitar_3d.json"
    run_fem_3d_simulation(str(test_config))